# https://toscrape.com/
# Scrapping Everything on This Website
'''
Bookstoscrape is Done 

Next is Quote_To_Scrape
    0. Micro Data with Pagination
    1. Log in With CRSF Token
    2. Javascript Generated Content
    3. 
'''

'''Logging in Quote_to_Scrape'''
import requests


# Login_Website: https://quotes.toscrape.com/login
# Website to Scrape: https://quotes.toscrape.com/
params = {'username': 'Kristian', 'password': '12345'}
r = requests.post("https://quotes.toscrape.com/", data=params)
print(r.text)

# Results are 
'''
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
'''
'''
# Where does it take me"?
# What URL did i get from this? 

'''



'''

quote_to_scrape HTML 
<form action="/login" method="post" accept-charset="utf-8">
        <input type="hidden" name="csrf_token" value="kYTqDtaohFvHQCpzKcjdGgnRPJlsIOEZrfbMiSuyxWAXmLNwUeBV">
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
        </div>
        <input type="submit" value="Login" class="btn btn-primary">
        
    </form>

Book HTML 
<form method="post" action="processing.php">
First name: <input type="text" name="firstname"><br>
Last name: <input type="text" name="lastname"><br>
<input type="submit" value="Submit" id="submit">
</form>

# They are Both When getting the password and username
# but it lies within the crsft Token 

What is A CSRF token (Cross-Site Request Forgery token) 
is a security mechanism used to prevent CSRF attacks. It is a unique, secret, and unpredictable value generated by the server 
and included in forms or requests to verify that the request is coming from a trusted source (the legitimate user).

'''

